### ISSUE TITLE
Introduce the gitlab screenshot

### ISSUE THREAD

**Issue by Vampouille** [acampergue-camptocamp/blog-article-cicd#4]
We don't known if it's a sonarqube or gitlab screenshot:
![Capture d’écran du 2023-04-04 10-33-44](https://user-images.githubusercontent.com/7067560/229735570-27cf7b60-9459-414d-8f7c-71458ef2dc07.png)

**Comment by acampergue-camptocamp** [comment]
fixed in commit 4ec2924
