### ISSUE TITLE
As I remember, tag is not used

### ISSUE THREAD

**Issue by Vampouille** [acampergue-camptocamp/blog-article-cicd#5]
![Capture d’écran du 2023-04-04 10-48-13](https://user-images.githubusercontent.com/7067560/229739213-625e2700-1a23-4351-bb3e-c46de158d43f.png)

**Comment by acampergue-camptocamp** [comment]
we are :

read here:
https://gitlab.devops.telekom.de/geo-hub/platforms/gdi-otc/cicd/gitlab-share/-/blob/feature/knowledge_transfer_and_documentation_branch/scripts/cicd-functions.sh?ref_type=heads#L1917

used there during the templating
https://gitlab.devops.telekom.de/geo-hub/platforms/gdi-otc/cicd/gitlab-share/-/blob/feature/knowledge_transfer_and_documentation_branch/scripts/cicd-functions.sh?ref_type=heads#L1954

to be finally used by skopeo there : https://gitlab.devops.telekom.de/geo-hub/platforms/gdi-otc/cicd/gitlab-share/-/blob/feature/knowledge_transfer_and_documentation_branch/.gitlab-ci-build-image-template-dev-finalize.bash#L33
