### ISSUE TITLE
docker-compose is used a standard

### ISSUE THREAD

**Issue by Vampouille** [acampergue-camptocamp/blog-article-cicd#6]
From my point of view, `docker-compose` is used:
* as a standard: devs can use it on workstation, pipeline should have the same behaviour
* to be able to use build parameters
* to build several images

It's a kind of devops interface

**Comment by Vampouille** [comment]
the pipeline may builds more than one image: 
![Capture d’écran du 2023-04-04 10-53-57](https://user-images.githubusercontent.com/7067560/229740709-fd95e5d1-ab2f-4eae-a84c-a055f09ed849.png)

**Comment by acampergue-camptocamp** [comment]
fixed in commit 843bb5c
