### ISSUE TITLE
Change font 

### ISSUE THREAD

**Issue by Vampouille** [acampergue-camptocamp/blog-article-cicd#7]
![Capture d’écran du 2023-04-04 10-55-29](https://user-images.githubusercontent.com/7067560/229741070-283e9cd1-55a6-49f5-8cfa-2e3e48b50942.png)

**Comment by acampergue-camptocamp** [comment]
I assume it meant that docker-compose.yml should appear as "code" instead of plain text, this was done in commit c2703cf
