### ISSUE TITLE
Maybe it could be interesting to talk about link to gitops

### ISSUE THREAD

**Issue by Vampouille** [acampergue-camptocamp/blog-article-cicd#9]
Using git to track upstream image update allows to have a full history of upstream images change
![Capture d’écran du 2023-04-04 10-59-52](https://user-images.githubusercontent.com/7067560/229742475-5f3cd324-5df4-44e0-b7e0-91aca844d3b2.png)

**Comment by acampergue-camptocamp** [comment]
Can you detail a little bit your idea ?

**Comment by acampergue-camptocamp** [comment]
fixed in d7b5abc
